### ISSUE TITLE
Cannot run the sample

### ISSUE THREAD

**Issue by juszkiem** [SyncfusionExamples/working-with-wpf-docking-manager-and-mvvm#2]
Cannot run the sample. It seems to be the issue with references. Can someone rework this to work with Core 5.0?

**Comment by JeganRavichandran** [comment]
Hi @juszkiem,

The reported issue is now resolved.
https://github.com/SyncfusionExamples/working-with-wpf-docking-manager-and-mvvm/pull/3/files 

We are closing this issue, please reopen if you still face any issues.
